### ISSUE TITLE
Add magazin to weapon on loading

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/grad-loadout.fork#10]
Add a magazin to the wapon when loading the loadout using extra parameters so that the missionbuilder can decide if he wants to use it. Example:
`
 
- primaryWeapon = "";
  -  primaryWeaponMuzzle = "";
  -  primaryWeaponOptics = "";
  -  primaryWeaponPointer = "";
  -  primaryWeaponUnderbarrel = "";
  -  primaryWeaponMag=""
-  secondaryWeapon = "";
   -  secondaryWeaponMag = "";
-  handgunWeapon = "LIB_P38";
   -  handgunWeaponMag="";

`

**Comment by Fusselwurm** [comment]
https://github.com/gruppe-adler/grad-loadout/blob/master/functions/extract/fn_ExtractLoadoutFromConfig.sqf

**Comment by Fusselwurm** [comment]
https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_hashToUnitLoadout.sqf

**Comment by Fusselwurm** [comment]
I will probably do something else here: 

* have global "loadWeapons" flag
* if that's set, pre-load weapons if appropriate magazine is found in config.

**Comment by Fusselwurm** [comment]
on second thought – no. As items are defined per-container (uniform, vest, backpack), extracting a mag from one of them would only add confusion for the loadout author, as they'd have to incorporate that into their calculation ("does that still fit into the loadout? where do I have to put it for it to be loaded into the weapon?")

**Comment by Fusselwurm** [comment]
fixed with #13
