### ISSUE TITLE
error in hashToUnitLoadout

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-loadout.fork#15]
## Scenario

1. [`_setEmptyParentArrayIfEmptyString` is called for `"addItemsToVest"`](https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_hashToUnitLoadout.sqf#L167) 
2. [`_setEmptyParentArrayIfEmptyString` calls `_walkIntoArray` with params `[_unitLoadout,_indices]`](https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_hashToUnitLoadout.sqf#L87)
3. [`_walkIntoArray`](https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_hashToUnitLoadout.sqf#L42) produces "Error Undefined variable in expression: _array"
4. and subsequently, because the return value is compared to a string, [this line](https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_hashToUnitLoadout.sqf#L88) produces "Error Undefined variable in expression: _testvalue"

## Explanation
* `_unitLoadout` is:  
`[[],[],[],["rhs_uniform_df15",[]],[],[],"","",[],["","","","","",""]]`

* `_indices` for "addItemsToVest" are:  
`[4,0]`

So because our unit's loadout doesn't have a vest, the vest array is empty. After the first forEach loop, `_array` is `[]` and after the second forEach loop, `_array` is `nil`. The error is thrown when `_walkIntoArray` attempts to return `_array`.

```sqf
_walkIntoArray = {
    params ["_array", "_indices"];
    
    {
        _array = _array select _x;
    } forEach _indices;

    _array
};
```
## However...
... this only happens when I call [fnc_doLoadout from here](https://github.com/gruppe-adler/TvT_UrbanOps.Altis/blob/master/functions/buyables/fn_equipAI.sqf#L60), which skips grad-loadout's whole extraction part and instead takes the loadout from 

```sqf
class cfgAIUnitLoadouts {
    class ind_me_terrorists {
        class marksman {
            uniform = "rhs_uniform_df15";
        };
    };
};
```

## Question
To me this looks like an oversight in grad-loadout's code. If that were the case though, why does the normal loadout procedure not throw any errors? So my question is:

Is this something that has to be fixed in grad-loadout or is my code at fault? If so, where is the mistake I'm making?

**Comment by nomisum** [comment]
even your questions are beautiful 😍

**Comment by McDiod** [comment]
Okay, so the workaround is this:

```sqf
class cfgAIUnitLoadouts {
    class ind_me_terrorists {
        class marksman {
            uniform = "rhs_uniform_df15";
            vest = "";
            backpack = "";
        };
    };
};
```

I am not entirely sure why this works and simply omitting `vest`and `backpack` does not. I'm also not sure if this hints at a bug in grad-loadout that just never shows up in our use cases. Can be closed if not.
