### ISSUE TITLE
NVITEM is not applied

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/grad-loadout.fork#19]
When defined in factions, it is not applied to units properly. Replicable with COOP Template, USOCP/USUCP loadout.

Any combination of options, with or without `#define NIGHTVISION` in USER/loadouts.hpp enabled or disabled. With NVITEM=""; or rhs goggles.

`nvgoggles = NVITEM;` or `nvgoggles = "";`  does not seem to make any difference for this behaviour.

Behaviour: Some units get their NVG removed ~2-5s after mission launch. Some units don't. Riflemen (and SQL AI) seem to get NVG removed, other units (Combat Life Saver/SQL Player) do not.

**Comment by McDiod** [comment]
Can't confirm, works for me. Is it only AI or players as well? AI units getting their NVG removed is an ASR AI feature iirc.

**Comment by SlantX** [comment]
Players as well. Can be seen in this mission: https://github.com/SlantX/CO_BD2.lythium

**Comment by SlantX** [comment]
RPT Snippet from my latest project:
https://pastebin.com/n27S0vp5

**Comment by SlantX** [comment]
Bug was caused in GRAD Factions. I applied a [bugfix](https://github.com/gruppe-adler/grad-factions/pull/14), which seems to have solved the issue. Closing this.
