### ISSUE TITLE
Defactionizer breaks with Pacific units

### ISSUE THREAD

**Issue by SlantX** [gruppe-adler/grad-loadout.fork#24]
GRAD Loadout is not applied to pacific units. Presumably because of the class name format.

`B_T_Soldier_F` (pacific) compared to the standard `B_Soldier_F`.

**Comment by McDiod** [comment]
You used

`["BLU_T_F", "classThatContainsYourLoadouts"] call GRAD_Loadout_fnc_FactionSetLoadout`

and then 

```
class classThatContainsYourLoadouts{
    class Type {
        class Soldier_F {
            ...
```


?

**Comment by SlantX** [comment]
I have uploaded the relevant .hpp here.

https://pastebin.com/dkppiX5E

**Comment by McDiod** [comment]
The problem here is that `B_T_Soldier_F` and `B_Soldier_F` are of the same type (`Soldier_F`) but of different factions (`BLU_T_F` vs. `BLU_F`).

The CO_Template doesn't come with an option to choose which factions loadouts are applied to and *only* applies them to `BLU_F`.
