### ISSUE TITLE
loadout self test

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/grad-loadout.fork#25]
loadout self-test function: should tell you problems like:

* does all the stuff really fit into the backpack?

for that, automatically spawn a unit of `<selectable>`  class/rank/something, or have the user select an existing unit; apply loadout and counter-check. 
restriction: doesnt work with loadouts using Player filter

**Comment by nomisum** [comment]
there is already a vanilla RPT entry when something doesnt fit into the backpack iirc.

**Comment by dedmen** [comment]
>there is already a vanilla RPT entry when something doesnt fit into the backpack iirc.

Not if you mean adding items via script.

You don't even need the unit for that test.
You can get the capacity of uniform/vest/backpack via config.
and the mass of all items too.
You can just math it out. Even offline.

**Comment by nomisum** [comment]
For me its more interesting to see a complete list of every unit with their according loadout in respective containers.

Yes, you could just scan the loadout.hpp, but the actual outcome could be different (e.g. wrong inheritance like in BC some weeks ago).

**Comment by McDiod** [comment]
Can be closed with #31 , which adds this:

>loadout self test

and this:

> a complete list of every unit with their according loadout in respective containers

but doesn't add this:

>for that, automatically spawn a unit of <selectable> class/rank/something, or have the user select an existing unit

Let's move discussion over there, if necessary.
