### ISSUE TITLE
add a random choice for uniforms/vests/backpacks/helmets

### ISSUE THREAD

**Issue by Salbei2500** [gruppe-adler/grad-loadout.fork#32]
It would be awesome if somebody could add he ability to give the system an array of items (uniforms/vests/backpacks/helmets) and let the system pick one and use it.

**Comment by nomisum** [comment]
whats the difference to the loadout reviver? i think randomizing before was quite a task

**Comment by Salbei2500** [comment]
I don't really know what the reviver does, but have a look at PR #33
