### ISSUE TITLE
new adding weapons to backpack functionality not selective enough

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-loadout.fork#36]
fn_normalizeContent checks `addItemsToBackpack` for weapon classnames and turns them into a weapons+accessory array for `setUnitLoadout`. See here:

https://github.com/gruppe-adler/grad-loadout/blob/master/functions/general/fn_normalizeContent.sqf#L26

However, most items are `cfgWeapons` subclasses, so the function takes `rhs_m4a1_grip_acog2` or `ACE_salineIV` and turns it into `["rhs_m4a1_grip_acog2","","","","","",""]` or `["ACE_salineIV","","","","","",""]`. 

Function needs to be able to differentiate between (rifles / handguns / launchers) and everything else.

**Comment by dedmen** [comment]
config `type` entry is the answer. Or just BIS_fnc_itemType

**Comment by Salbei2500** [comment]
@dedmen beziehst du dich dabei auf den Fehler oder den fix?

**Comment by dedmen** [comment]
Den fix. Mit BIS_fnc_itemType kann man erkennen ob es wirklich eine Waffe sind.
Denn grip's und ACE items (ace items sind bipods afaik) sind keine waffen.
Das ist das was das Arsenal benutzt zum einordnen.

**Comment by Salbei2500** [comment]
Changed the PR
