### ISSUE TITLE
documentation for #33 randomization

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-loadout.fork#41]

**Comment by Salbei2500** [comment]
There is a documentation: https://github.com/gruppe-adler/grad-loadout/blob/master/README.md#random-selection

**Comment by nomisum** [comment]
hmmm

maybe remove or comment on https://github.com/gruppe-adler/grad-loadout/blob/master/README.md#grad_loadout_fnc_addreviver

**Comment by Salbei2500** [comment]
What would you change on the addReviver documentation?
