### ISSUE TITLE
resetLoadout = 0 --> original Magazine in loadout weapon

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-loadout.fork#8]
When using `resetLoadout = 0`, a magazine of the unit's original weapon is loaded into the new weapon.

![loschmich](https://cloud.githubusercontent.com/assets/16549968/19568343/7def10da-96f1-11e6-8d3e-a2ffdf037e66.jpg)

**Comment by Fusselwurm** [comment]
fixed in ef183dbc1d40f9495a598ee83968454a7f01d8db , released 4.2.1
